### ISSUE TITLE
sessionListener doesn't contain current media

### ISSUE THREAD

**Issue by JumBay** [miloproductionsinc/cordova-plugin-chromecast#5] opened 2019-11-24 15:56 UTC
Hi,

First of all thanks for this great work.

I'm testing your [example](https://github.com/miloproductionsinc/cordova-plugin-chromecast/blob/master/doc/example.js) on an ios simulator. It works, but I've noticed when the `sessionListener` [is called](https://github.com/miloproductionsinc/cordova-plugin-chromecast/blob/master/doc/example.js#L14) on a restart, for example, the `media` property is always an empty array even if something is playing.

Is there any way to retrieve the current media?

Thx again

**Comment by Lindsay-Needs-Sleep** [comment] 2019-11-25 21:57
Thanks for testing it out and posting this!

I have confirmed the error.  It is being tricky to solve though.  I will get back to you!

**Comment by Lindsay-Needs-Sleep** [comment] 2019-12-02 08:30
@JumBay Sorry for the delay!  I started working on the issue and uncovered quite a few other things.  But I believe this issue is now fixed!
Please let me know if if you are still seeing the problem!

**Closed as completed by Lindsay-Needs-Sleep** 2019-12-02 08:30 UTC

**Comment by JumBay** [comment] 2019-12-02 08:43
Great, thank you, I'll have a look

**Comment by Lindsay-Needs-Sleep** [comment] 2019-12-03 09:43
(Just an fyi, I made a couple more updates because I found another bug where ios loaded media is not detected on android).

**Comment by JumBay** [comment] 2019-12-03 20:24
Ok, I won't be able to test for the next two weeks

**Comment by JumBay** [comment] 2019-12-27 13:21
I've been able to test, now we have the media, but the listener `media.addUpdateListener` doesn't work and the media doesn't seem to be updated. I've only tested on an iOS simulator:
```js
 document.addEventListener('deviceready', function() {
      // Must wait for deviceready before using chromecast

      // File globals
      var _session = null;
      var _media = null;

      initialize();

      function initialize() {
        // use default app id
        var appId = chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID;
        var apiConfig = new chrome.cast.ApiConfig(new chrome.cast.SessionRequest(appId), function sessionListener(session) {
          // The session listener is only called under the following conditions:
          // * will be called shortly chrome.cast.initialize is run
          // * if the device is already connected to a cast session
          // Basically, this is what allows you to re-use the same cast session
          // across different pages and after app restarts

          // Got a session!
          _session = session;

          if (session.media.length > 0) {
            _media = session.media[0];
            console.log('_media', { _media });
            mediaAddUpdateListener();
          }

          console.log('session from initialize', session);

        }, function receiverListener(receiverAvailable) {
          // receiverAvailable is a boolean.
          // True = at least one chromecast device is available
          // False = No chromecast devices available
          // You can use this to determine if you want to show your chromecast icon
        });

        // initialize chromecast, this must be done before using other chromecast features
        chrome.cast.initialize(apiConfig, function() {
          // Initialize complete
          // Let's start casting

          setTimeout(() => {
            if (!_session) {
              requestSession();
            } else if (!_media) {
              loadMedia();
            }
          }, 2000);
        }, function(err) {
          // Initialize failure
        });
      }


      function requestSession() {
        console.log('requestSession');

        // This will open a native dialog that will let
        // the user choose a chromecast to connect to
        // (Or will let you disconnect if you are already connected)
        chrome.cast.requestSession(function(session) {
          console.log('session from requestSession', session);

          // Got a session!
          _session = session;

          loadMedia();
        }, function(err) {
          console.log('failed to request session', err);
          // Failed, or if err is cancel, the dialog closed
        });
      }

      function loadMedia() {
        console.log('loadMedia');

        var videoUrl = 'https://ia801302.us.archive.org/1/items/TheWater_201510/TheWater.mp4';
        var mediaInfo = new chrome.cast.media.MediaInfo(videoUrl, 'video/mp4');

        _session.loadMedia(new chrome.cast.media.LoadRequest(mediaInfo), function(media) {
          // You should see the video playing now!
          // Got media!
          _media = media;

          mediaAddUpdateListener();

          // Wait a couple seconds
          setTimeout(function() {
            // Lets pause the media
            pauseMedia();
          }, 4000);

        }, function(err) {
          // Failed (check that the video works in your browser)
        });
      }

      function mediaAddUpdateListener() {
        _media.addUpdateListener(isAlive => {
          console.log('isAlive', isAlive, { _media });
        });
      }

      function pauseMedia() {
        _media.pause({}, function() {
          // Success

          // // Wait a couple seconds
          setTimeout(function() {
            // stop the session
            // stopSession();

            document.location.reload();
          }, 2000);

        }, function(err) {
          // Fail
        });
      }

      function stopSession() {
        // Also stop the session (if )
        _session.stop(function() {
          // Success
        }, function(err) {
          // Fail
        });
      }

    });

**Comment by Lindsay-Needs-Sleep** [comment] 2020-01-03 07:06
Sorry, the holidays have been very busy.  I will try to take a look within the week.

**Comment by Lindsay-Needs-Sleep** [comment] 2020-01-14 01:44
Sorry, a lot of stuff came up.

I just tried out the code on the most recent version of the plugin.  It appears that the media.addUpdateListener is called.  It is also updated when the pause event occurs.

I changed 
`console.log('isAlive', isAlive, { _media });` 
to 
`console.log('media Update: ' + _media.currentTime + ": " +  _media.playerState);`

and commented out `document.location.reload();` (so that I could have time to examine the output)

Here is what I got:

![Screen Shot 2020-01-13 at 6 28 24 PM](https://user-images.githubusercontent.com/51773923/72305908-85d7d280-3632-11ea-9c3e-c9d534504550.png)

Importantly, you can see these 3 lines:
```
[Log] media Update: 0: PLAYING 
[Log] media Update: 0.794208: PLAYING 
[Log] media Update: 4.10542: PAUSED
```

I tested this on an actual iPhone5 (ios 10), and Android 6 device.

 In the automatic test suite, there are many tests that depend on `media.addUpdateListener`.  I have run these successfully for ios 9,10,12 (actual device), ios 13 (emulator).

I think it should be working fine. :S

What ios version + device are you emulating?
Maybe you can try running the tests and tell me the output?

To run the tests:
* update cordova-plugin-chromecast (recent bug fix)
* `cordova plugin add ./node_modules/cordova-plugin-chromecast/tests`
* in `config.xml` set `<content src="plugins/cordova-plugin-chromecast-tests/www/html/tests.html" comment="plugins/cordova-plugin-chromecast-tests/www/html/tests.html" />`

**Comment by JumBay** [comment] 2020-01-14 11:55
Hi,

Sorry, I may have forgotten to mention that it doesn't work on reload, hence the `document.reload()`, but I'll test on the latest release and let you know.

**Comment by JumBay** [comment] 2020-01-15 20:16
I did the test on a simulator and an iPhone 6s with both the latest iOS version and when the app reload (document.reload) we cannot interact with the media element

**Comment by Lindsay-Needs-Sleep** [comment] 2020-01-16 02:07
okay, I'll take another look!
Ah, yeah, okay, I can replicate it!

**Comment by Lindsay-Needs-Sleep** [comment] 2020-01-16 07:51
Okay, I think I have fixed it!
Can you try it again?

**Comment by JumBay** [comment] 2020-01-16 17:17
Great job it works.
Thanks.

**Comment by JumBay** [comment] 2020-01-18 12:30
I did find another similar issue.
Cast something, kill the app, reopen it. The session will be retrieved, the media will be retrieved as well with the right `playerState` but you cannot interact with the media object anymore, play, pause... methods have no effect.

**Comment by JumBay** [comment] 2020-01-20 21:03
In the latest update 372cfeed39c3b77d568abfc68a5904a2a7af6ec6 the session is not retrieved on app restart (still iOS testing)

**Comment by Lindsay-Needs-Sleep** [comment] 2020-01-21 00:49
Oh gee, yep.  I thought I had that covered.  Turns out I made a mistake writing the test that covers this case. poo.

Thanks for the report!

I'm going to make another [issue](https://github.com/miloproductionsinc/cordova-plugin-chromecast/issues/6) for this.
